output_path: inferences/turbo_default_bc_tmp0.25_delete_me
task_type: inference
data:
    val_split:
        dataset_type: grid_bc
        path: null
        start: 0
        end: 10_000
        noise: false
        scaling: 1.0
model:
    name: whisper
    model_type: large-v3-turbo
    path:
debug: true
extract_logprobs: true
word_timestamps: true
beam_size: 5
subword_timestamps: true
temperature: .5
runs_per_sample: 5
