[Config]
model = whisper
model_type = tiny
model_path =
output_path = inferences/tmp

dataset_type = grid
dataset_path = datasets/grid/
train_split = 100
test_split = 100
val_split = 30

#for debugging
dataset_scaling = 1
debug = False

[InferenceConfig]
extract_logprobs = True
word_timestamps = True
beam_size = 5,2