[Config]
model = parakeet
model_type = ctc-0.6b
model_path =
output_path = inferences/delete_me

dataset_type = grid_bc
dataset_path =
add_noise = False
train_split = 0
test_split = 0
val_split = 10

#for debugging
dataset_scaling = 1
debug = True

[InferenceConfig]
extract_logprobs = False
word_timestamps = False
beam_size = 5