[Config]
model = whisper
model_type = large-v3-turbo
model_path =
output_path = inferences/delete_me

dataset_type = grid_bc
dataset_path =
add_noise = False
train_split = 0
test_split = 0
val_split = 1.

#for debugging
dataset_scaling = 1
debug = False

[InferenceConfig]
extract_logprobs = True
word_timestamps = True
beam_size = 5