output_path: inferences/base_exp_dispersion_delete_me
task_type: inference
data:
    train_split: null
    test_split: null
    val_split:
        dataset_type: grid_bc
        path: null
        start: 0
        end: 1000
        noise: false
        scaling: 1.0
model:
    name: whisper
    model_type: base
    path: trained_models/base_exp
debug: true
extract_logprobs: true
word_timestamps: true
beam_size: 5
subword_timestamps: true
temperature: 0
runs_per_sample: 1
dispersion: true
