[Config]
model = whisper
model_type = tiny
model_path = trained_models/training_output_test_folder
output_dir = inferences/tmp

dataset_path = datasets/grid/
train_split = 0.7
test_split = 0.2
val_split = 0.1

#for debugging
dataset_scaling = 0.005
debug = True

[InferenceConfig]

#extract_logits = True