[Config]
model = whisper
model_type = tiny
dataset_path = datasets/grid/
train_split = 0.7
test_split = 0.2
val_split = 0.1
output_dir = trained_models/training_output_test_folder

#for debugging
dataset_scaling = 0.005

[TrainingConfig]

perform_training = False
learning_rate = 1e-5
num_train_epochs = 1
warmup_steps = 500