[Config]
model = whisper
model_type = tiny
model_path =
output_path = trained_models/training_output_test_folder

dataset_path = datasets/grid/
train_split = 0.01
test_split = 0.2
val_split = 0.79

#for debugging
dataset_scaling = 0.005
debug = True

[TrainingConfig]
perform_training = True
learning_rate = 1e-5
num_train_epochs = 1
warmup_steps = 500