output_path: finetuned_models/base
task_type: training
data:
    train_split:
        dataset_type: grid
        path:   datasets/grid_with_noise_without_bc_sentences
        start: 0
        end: 10
        noise: true
        scaling: 1.
    val_split:
        dataset_type: grid_bc
        path: datasets/grid_bc_without_duplicates
        start: 0
        end: 10
        noise: false
        scaling: 1.
model:
    name: parakeet
    model_type: ctc-0.6b
    path: null
debug: false
perform_training: true
learning_rate: 1.0e-05
num_train_epochs: 2
batch_size: 16
save_and_eval_steps: 100
warmup_steps: 500
